### ISSUE TITLE
can we add sound with push notification.

### ISSUE THREAD

**Issue by naveen84123** [Altaibaatar/APNS-with-auth-key-p8-using-PHP#3]
code is showing the push notification. 
but is it possible to set the sound tone with this?

**Comment by naveen84123** [comment]
gotcha. thanks.

**Comment by Altaibaatar** [comment]
Yes. Default tone can be fired with json shown below.
```
{
    "aps" :     {
        "alert" : "Test Push Message",
        "sound" : "default"
    };
}
```
So I think, You should add a line of code below

```
...
$arSendData['aps']['alert']['sound'] = sprintf("default"); // default notification sound
$sendDataJson = json_encode($arSendData);
...
```


There is a great tutorial for playing custom sound...

https://medium.com/@dmennis/the-3-ps-to-custom-alert-sounds-in-ios-push-notifications-9ea2a2956c11

**Comment by naveen84123** [comment]
$arSendData['aps']['sound'] = 'default'; it is working like this.
