### ISSUE TITLE
iPhone does not show notification

### ISSUE THREAD

**Issue by nQk2** [Altaibaatar/APNS-with-auth-key-p8-using-PHP#4]
Hello,
I had been using this script for quite a while and it was always working.
But since recently my iPhone sometimes stops receiving the notifications.
Workaround: Run Xcode, start app and connect iPhone.

Any ideas?

**Comment by Altaibaatar** [comment]
Hello
I think you should check your device token whether it's same as the token you sending notification or not. I'm suspecting that your device token had changed after the installation and it's not registered on your server.
I've checked the program using this script on iOS12 and iOS 13 devices. Everything seems fine. If you find something, please let me know.

Regards,

**Comment by nQk2** [comment]
I noticed a strange behaviour. So apparently while my iPhone is providing a Personal Hotspot, it doesn't receive the notifications. When I turn off the hotspot, the "pending" notifications are flushed through and shown (but not always).
Can you confirm this?
