### ISSUE TITLE
How can i send VOIP push using your code?

### ISSUE THREAD

**Issue by warisappify** [Altaibaatar/APNS-with-auth-key-p8-using-PHP#6]
Hi,

This is very help full in case of APNS.
Can you please add method to use pem file with your code or how to send voip push using this utility.

Thanks in advance.

**Comment by Altaibaatar** [comment]
Thank you for your comment, @warisappify. 
Recently, I am not working on this project and don't have the environment to test additional functions and changes.
I hope you can find a different solution.

Have a great day!
